project_id = "aswejhthjhhawxetjyhz"

[functions.parse-portfolio]
verify_jwt = false

[functions.parse-email]
verify_jwt = false

[functions.amarstock-proxy]
verify_jwt = false

[functions.fetch-mds-prices]
verify_jwt = false

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-callback]
verify_jwt = false

[functions.gmail-fetch-emails]
verify_jwt = false

[functions.gmail-disconnect]
verify_jwt = false
